import type { Card, CardType, Effect, WorldEvent } from "./types";
export const TYPE_LABEL: Record<CardType, string> = {
  shift: "人格漂移",
  attack: "搞事牌",
  defense: "反制牌",
  strategy: "策略牌",
  special: "特殊牌",
};
export const AXIS_LETTERS = [
  ["E", "I"],
  ["S", "N"],
  ["T", "F"],
  ["J", "P"],
] as const;
export const AXIS_NAMES = [
  ["向外充电", "独处回血"],
  ["脚踏实地", "脑洞大开"],
  ["理性在线", "感受优先"],
  ["按计划来", "随心就好"],
] as const;
export const PERSONALITIES = [
  "INTJ",
  "INTP",
  "ENTJ",
  "ENTP",
  "INFJ",
  "INFP",
  "ENFJ",
  "ENFP",
  "ISTJ",
  "ISFJ",
  "ESTJ",
  "ESFJ",
  "ISTP",
  "ISFP",
  "ESTP",
  "ESFP",
];
const shiftRows: [string, string, 0 | 1 | 2 | 3, number, string][] = [
  ["今晚出来玩吗？", "就出来坐五分钟。", 0, -2, "party"],
  ["周末失联", "消息已读，人已消失。", 0, 2, "moon"],
  ["跟外卖员聊半小时", "饭凉了，关系热了。", 0, -3, "chat"],
  ["社交电量不足", "不是讨厌你，是没电了。", 0, 3, "battery"],
  ["眼见为实", "别画饼，给我看看。", 1, -2, "eye"],
  ["如果月亮是芝士", "先别管合不合理。", 1, 2, "planet"],
  ["先把饭吃了", "宇宙的事，饭后再说。", 1, -3, "food"],
  ["脑内小剧场", "你只说了句“哦”。", 1, 3, "cloud"],
  ["先别哭，我帮你分析", "解决问题也是一种爱。", 2, -2, "chart"],
  ["抱一下再说", "道理等会儿再讲。", 2, 2, "heart"],
  ["数据不会骗人", "但汇报的人会。", 2, -3, "chart"],
  ["看到小狗就走不动", "原则？什么原则？", 2, 3, "heart"],
  ["十八页旅行攻略", "连迷路都有备用路线。", 3, -3, "map"],
  ["到了机场再订酒店", "先出发，世界会给答案。", 3, 3, "plane"],
  ["待办清单清零", "今日快乐，全部打勾。", 3, -2, "check"],
  ["计划就是没有计划", "随便逛逛也挺好。", 3, 2, "dice"],
  ["我来开个场", "尴尬不存在的。", 0, -1, "mic"],
  ["一个人的电影院", "旁边的座位留给爆米花。", 0, 1, "moon"],
  ["这事得讲逻辑", "情绪暂时靠边站。", 2, -1, "brain"],
  ["我懂你的意思", "没说出口的也懂。", 2, 1, "heart"],
];
export const CARDS: Card[] = shiftRows.map(
  ([name, flavor, axis, amount, art], i) => ({
    id: `s${i}`,
    name,
    flavor,
    description: `向 ${AXIS_LETTERS[axis][amount < 0 ? 0 : 1]} 漂移 ${Math.abs(amount)} 格`,
    type: "shift",
    target: "any",
    effects: [{ kind: "move", axis, amount }],
    rarity: Math.abs(amount) === 3 ? "稀有" : "日常",
    tags: axis === 0 ? ["社交"] : ["生活"],
    art,
    animation: "drift",
  }),
);
function add(
  id: string,
  name: string,
  flavor: string,
  description: string,
  type: CardType,
  target: Card["target"],
  effects: Effect[],
  art: string,
  rarity: Card["rarity"] = "稀有",
  tags: string[] = [],
) {
  CARDS.push({
    id,
    name,
    flavor,
    description,
    type,
    target,
    effects,
    art,
    rarity,
    tags,
    animation:
      type === "attack" ? "impact" : type === "defense" ? "guard" : "twist",
  });
}
add(
  "a0",
  "临时加班",
  "下班前五分钟，有个小需求。",
  "让对方向 J 漂移 2 格",
  "attack",
  "other",
  [{ kind: "move", axis: 3, amount: -2 }],
  "laptop",
);
add(
  "a1",
  "强制团建",
  "这次真的全员自愿。",
  "让对方向 E 漂移 3 格",
  "attack",
  "other",
  [{ kind: "move", axis: 0, amount: -3 }],
  "party",
  "稀有",
  ["社交"],
);
add(
  "a2",
  "手机没电",
  "你的世界突然安静。",
  "对方下回合不能使用人格能力",
  "attack",
  "other",
  [{ kind: "skip" }],
  "battery",
);
add(
  "a3",
  "计划赶不上变化",
  "惊喜是惊，喜不一定。",
  "让对方向 P 漂移 3 格",
  "attack",
  "other",
  [{ kind: "move", axis: 3, amount: 3 }],
  "dice",
);
add(
  "a4",
  "你想太多了",
  "对方正在输入一部小说。",
  "让对方向 N 漂移 2 格",
  "attack",
  "other",
  [{ kind: "move", axis: 1, amount: 2 }],
  "cloud",
);
add(
  "a5",
  "别做梦了",
  "老板：回到现实。",
  "让对方向 S 漂移 2 格",
  "attack",
  "other",
  [{ kind: "move", axis: 1, amount: -2 }],
  "eye",
);
add(
  "a6",
  "深夜情感电台",
  "有人哭了，我不说是谁。",
  "让对方向 F 漂移 3 格",
  "attack",
  "other",
  [{ kind: "move", axis: 2, amount: 3 }],
  "heart",
);
add(
  "a7",
  "这锅你背一下",
  "突然开始独立思考。",
  "让对方向 T 漂移 3 格",
  "attack",
  "other",
  [{ kind: "move", axis: 2, amount: -3 }],
  "chart",
);
add(
  "a8",
  "群聊突然冷场",
  "刚才不是聊得挺好吗？",
  "让对方向 I 漂移 2 格",
  "attack",
  "other",
  [{ kind: "move", axis: 0, amount: 2 }],
  "chat",
  "日常",
  ["社交"],
);
add(
  "a9",
  "凌晨两点老板发消息",
  "“在吗？” 你最好不在。",
  "让对方向 J、I 各漂移 1 格",
  "attack",
  "other",
  [
    { kind: "move", axis: 3, amount: -1 },
    { kind: "move", axis: 0, amount: 1 },
  ],
  "phone",
  "限定",
);
add(
  "d0",
  "婉拒",
  "谢谢，但真的不用。",
  "抵消一次指向你的卡牌",
  "defense",
  "self",
  [{ kind: "shield" }],
  "hand",
);
add(
  "d1",
  "已读不回",
  "沉默就是我的态度。",
  "抵消一次卡牌；社交牌另抽 1 张",
  "defense",
  "self",
  [{ kind: "shield" }],
  "chat",
  "稀有",
  ["社交反制"],
);
add(
  "d2",
  "你说得都对",
  "所以，送还给你。",
  "将一次卡牌反弹给出牌者",
  "defense",
  "self",
  [{ kind: "reflect" }],
  "mirror",
);
add(
  "d3",
  "勿扰模式",
  "我的世界暂不营业。",
  "获得 1 层防护，并抽 1 张牌",
  "defense",
  "self",
  [{ kind: "shield" }, { kind: "draw", amount: 1 }],
  "moon",
);
add(
  "d4",
  "情绪稳定",
  "内心风浪，外表无事。",
  "抵消一次卡牌；向 T 漂移 1 格",
  "defense",
  "self",
  [{ kind: "shield" }, { kind: "move", axis: 2, amount: -1 }],
  "stone",
);
add(
  "d5",
  "边界感",
  "这边才是你的工位。",
  "获得 2 层防护",
  "defense",
  "self",
  [{ kind: "shield", amount: 2 }],
  "shield",
  "限定",
);
add(
  "d6",
  "反向操作",
  "这题我有自己的解法。",
  "反弹一次卡牌；向 P 漂移 1 格",
  "defense",
  "self",
  [{ kind: "reflect" }, { kind: "move", axis: 3, amount: 1 }],
  "reverse",
);
add(
  "d7",
  "我先下线了",
  "下次一定。",
  "抵消一次卡牌；向 I 漂移 1 格",
  "defense",
  "self",
  [{ kind: "shield" }, { kind: "move", axis: 0, amount: 1 }],
  "door",
);
add(
  "t0",
  "让我猜猜",
  "你的心思，漏了一点。",
  "偷看对方所选轴的秘密目标",
  "strategy",
  "other",
  [{ kind: "peek" }],
  "eye",
);
add(
  "t1",
  "不小心瞄到",
  "真的只是路过。",
  "偷看对方两张手牌",
  "strategy",
  "other",
  [{ kind: "peek", amount: 2 }],
  "cards",
);
add(
  "t2",
  "换位思考",
  "站在你的角度发疯。",
  "与对方交换所选人格轴",
  "strategy",
  "other",
  [{ kind: "swap" }],
  "mirror",
);
add(
  "t3",
  "你的就是我的",
  "借我用用，下次还。",
  "与对方交换一张手牌",
  "strategy",
  "other",
  [{ kind: "trade" }],
  "cards",
);
add(
  "t4",
  "再说一遍",
  "复读机也是一种态度。",
  "复制上张漂移牌；无记录则抽 2 张",
  "strategy",
  "any",
  [{ kind: "copy" }],
  "reverse",
);
add(
  "t5",
  "灵感补给",
  "脑子开始有画面了。",
  "抽 2 张牌",
  "strategy",
  "self",
  [{ kind: "draw", amount: 2 }],
  "coffee",
);
add(
  "t6",
  "顺手牵牌",
  "这张牌跟我比较熟。",
  "随机拿走对方一张手牌",
  "strategy",
  "other",
  [{ kind: "steal" }],
  "hand",
);
add(
  "t7",
  "重启一下",
  "刚刚那个我不算。",
  "把自己的所选轴翻转到另一侧",
  "strategy",
  "self",
  [{ kind: "reset" }],
  "reverse",
);
add(
  "x0",
  "人格伪装",
  "你看到的，未必是我。",
  "隐藏全部轨道并伪装人格至下回合",
  "special",
  "self",
  [{ kind: "mask" }],
  "mask",
  "限定",
);
add(
  "x1",
  "我真的没生气",
  "真的。你再问一遍试试。",
  "隐藏自己的轨道至下回合",
  "special",
  "self",
  [{ kind: "hide" }],
  "cloud",
);
add(
  "x2",
  "装 E 一天",
  "营业结束，概不售后。",
  "向 E 漂移 2 格，并抽 1 张",
  "special",
  "self",
  [
    { kind: "move", axis: 0, amount: -2 },
    { kind: "draw", amount: 1 },
  ],
  "party",
);
add(
  "x3",
  "随心所欲",
  "今天，我自己定义。",
  "所选轴朝秘密目标漂移 2 格",
  "special",
  "self",
  [{ kind: "wild", amount: 2 }],
  "star",
  "限定",
);
add(
  "x4",
  "社交蝴蝶",
  "全场都是我的熟人。",
  "向 E、F 各漂移 2 格",
  "special",
  "any",
  [
    { kind: "move", axis: 0, amount: -2 },
    { kind: "move", axis: 2, amount: 2 },
  ],
  "butterfly",
  "限定",
);
add(
  "x5",
  "宇宙级内耗",
  "一个人，八百个念头。",
  "向 I、N 各漂移 2 格",
  "special",
  "any",
  [
    { kind: "move", axis: 0, amount: 2 },
    { kind: "move", axis: 1, amount: 2 },
  ],
  "planet",
  "限定",
);
add(
  "x6",
  "再来亿次",
  "就最后一张，真的。",
  "本回合可额外出 1 张牌，并抽 1 张",
  "special",
  "self",
  [{ kind: "extra" }, { kind: "draw", amount: 1 }],
  "reverse",
  "限定",
);
add(
  "x7",
  "突然想通了",
  "脑子终于连上了网。",
  "向 S、T 各漂移 1 格，并抽 1 张",
  "special",
  "self",
  [
    { kind: "move", axis: 1, amount: -1 },
    { kind: "move", axis: 2, amount: -1 },
    { kind: "draw", amount: 1 },
  ],
  "brain",
  "限定",
);
export const CARD_MAP = Object.fromEntries(CARDS.map((c) => [c.id, c]));
export const EVENTS: WorldEvent[] = [
  {
    id: "annual",
    name: "公司年会",
    flavor: "今晚，内向的人无处可逃。",
    description: "所有向 E 的漂移额外 1 格",
    axis: 0,
    direction: -1,
    bonus: 1,
  },
  {
    id: "deadline",
    name: "Deadline 明早九点",
    flavor: "闹钟还没响，心已经凉了。",
    description: "J / P 轴漂移效果额外 1 格",
    axis: 3,
    bonus: 1,
  },
  {
    id: "cancel",
    name: "旅行计划突然取消",
    flavor: "十八页攻略，变成十八页遗憾。",
    description: "事件开始时，所有人向 P 漂移 1 格",
    bonus: 0,
  },
  {
    id: "heartbreak",
    name: "朋友凌晨失恋",
    flavor: "今晚没有理性，只有纸巾。",
    description: "所有向 F 的漂移额外 1 格",
    axis: 2,
    direction: 1,
    bonus: 1,
  },
  {
    id: "offline",
    name: "全城断网",
    flavor: "终于有了不回消息的理由。",
    description: "所有向 I 的漂移额外 1 格",
    axis: 0,
    direction: 1,
    bonus: 1,
  },
  {
    id: "brainstorm",
    name: "头脑风暴",
    flavor: "不落地也没关系，先飞。",
    description: "所有向 N 的漂移额外 1 格",
    axis: 1,
    direction: 1,
    bonus: 1,
  },
  {
    id: "review",
    name: "季度复盘",
    flavor: "请用数据解释你的快乐。",
    description: "所有向 T 的漂移额外 1 格",
    axis: 2,
    direction: -1,
    bonus: 1,
  },
  {
    id: "weekend",
    name: "终于周五了",
    flavor: "所有安排，周一再说。",
    description: "所有向 P 的漂移额外 1 格",
    axis: 3,
    direction: 1,
    bonus: 1,
  },
  {
    id: "grounded",
    name: "回到现实",
    flavor: "幻想暂停，先交房租。",
    description: "所有向 S 的漂移额外 1 格",
    axis: 1,
    direction: -1,
    bonus: 1,
  },
  {
    id: "gift",
    name: "意外的礼物",
    flavor: "命运偶尔也会发福利。",
    description: "事件开始时，所有人额外抽 1 张",
    bonus: 0,
  },
];
